name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Or your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Run test script
        run: npm test